#!/bin/sh
# saintless for Retro-Debian. Simple script to convert audio files to .mp3
# GNU GPL v3 applies. No warranty of any kind.
# Based on: https://github.com/MintPup/Retro-Debian-Sources/blob/master/scripts/video2mp3
# Works with audio and video files and can replace video2mp3.
# Depends on ffmpeg. Using mencoder to convert audio needs workaround I do not like.
# FYI workaround for mencoder: http://uselessdiaries.blogspot.bg/2008/04/converting-audio-files-to-mp3-using.html


if [ -z "which ffmpeg" ];then
echo "This script needs ffmpeg installed."
exit
fi

if [ "$1" = "--help" ] || [ "$1" = "-h" ]; then
echo
echo "Convert audio/video files from directory to .mp3"
echo "Choice for file extension and bitrate only."
echo "In terminal cd to the directory and type:"
echo "/path-to/all2mp3"
echo
exit
fi

read -p "Type file extension to convert: m4a, ogg, flv, avi : " EXT
read -p "Type bitrate in kb, like: 128 or 256 or 320: " BIT
echo
echo Convert all ."$EXT" with bitrate "$BIT"kb.
read -p "Is this correct? (y/n)?" choose
case "$choose" in
  y|Y ) (for FILE in *."$EXT" ; do ffmpeg -i "$FILE" -f mp3 -ab "$BIT"000 "$(basename "$FILE" ."$EXT")-new.mp3" || break; done);;
  * ) exit 0;;
esac

