#!/bin/sh
# 20170801 saintless for Retro-Debian and DebianDog.
# Option to save on exit in multiple directories for frugal install on ext partition using aufs.
# GNU GPL v3 applies. No warranty of any kind.
# 20170907 changes for Retro-Etch.

if [ "$(whoami)" != "root" ]; then
echo "You have to run this script as Superuser."
exit
fi

if  grep -q persistent /proc/cmdline || grep -q persistence /proc/cmdline; then
echo
echo "Boot without persistent or persistence and run the script again."
echo
exit
fi

BASE=$(pwd)
VER=etch     #easy to change with lenny, squeeze, wheezy later (without spaces to add entry properly in make_menu function).
SQFS=01-retro-"$VER".squashfs
DIR="10.dir"

if [ ! -f "$BASE"/"$SQFS" ]; then
echo "$SQFS" is missing.
echo "Find it and run the script from there."
exit
fi

echo
echo "For frugal install on EXT partition only !!! "
echo "Save session in subfolders from 10.dir to 99.dir"
echo in "$BASE" loaded on next boot.
echo

read -p "Do you want to continue (y/n)?" choose
case "$choose" in
  y|Y ) echo "Continue...";;
  * ) exit;;
esac

#NEXT= line source: https://stackoverflow.com/questions/1587059/bash-find-highest-numbered-filename-in-a-directory-where-names-start-with-digit
NEXT=$(ls "$BASE" | grep ".dir" | sort -rn | awk '{FS="_"; printf "%0d.dir\n",$1+1;exit}')

if [ ! -d "$BASE" ]; then
echo No "$BASE" found. Change BASE= to your boot folder name.
exit
fi

if [ ! -d "$BASE"/"$DIR" ]; then
echo Saving session in "$BASE"/"$DIR" ...
mkdir "$BASE"/"$DIR"
cp -ap /live/cow/* "$BASE"/"$DIR"
sync
echo "Done."
exit
else
echo Saving session in "$BASE"/"$NEXT" ...
echo "$NEXT"
mkdir "$BASE"/"$NEXT"
cp -ap /live/cow/* "$BASE"/"$NEXT"
sync
echo "Done."
fi

exit
