#!/bin/sh
# Running this script will start all executable scripts in $HOME/Startup directory.

if [ ! -d "$HOME"/Startup ]; then
mkdir -p "$HOME"/Startup
fi

find "$HOME"/Startup/* |  while read J
do
   "$J" &
done
